# Generated by Django 6.0.1 on 2026-01-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to='tickets.department')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket Assignments',
                'db_table': 'ticket_assigned',
                'unique_together': {('ticket', 'department')},
            },
        ),
    ]
