# Generated by Django 6.0.1 on 2026-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
