# Generated by Django 6.0.1 on 2026-01-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketmessage_hidden'),
        ('tickets', '0006_alter_user_profile_picture'),
    ]

    operations = [
    ]
