# Generated by Django 6.0.1 on 2026-01-30 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='tickets.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Departments',
                'db_table': 'user_departments',
                'unique_together': {('user', 'department')},
            },
        ),
    ]
