# Generated by Django 6.0.1 on 2026-01-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_department_description_department_slug'),
        ('tickets', '0007_userdepartments'),
    ]

    operations = [
    ]
