# Generated by Django 6.0.1 on 2026-01-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_merge_20260130_2052'),
        ('tickets', '0008_merge_20260130_1512'),
    ]

    operations = [
    ]
