# Generated by Django 6.0.1 on 2026-01-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketmessage_ticket'),
        ('tickets', '0010_ticket_uuid'),
    ]

    operations = [
    ]
