# Generated by Django 6.0.1 on 2026-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_merge_20260131_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
