# Generated by Django 6.0.1 on 2026-02-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-edited_at']},
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
