# Generated by Django 6.0.1 on 2026-02-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
