# Generated by Django 6.0.1 on 2026-02-11 17:56

from django.db import migrations, models
from django.utils.text import slugify


def populate_profile_slugs(apps, schema_editor):
    """Backfill unique profile slugs for existing users."""
    User = apps.get_model("tickets", "User")
    used = set()
    for user in User.objects.all().order_by("id"):
        base = slugify(user.username) or "user"
        slug = base
        i = 1
        while slug in used:
            i += 1
            slug = f"{base}-{i}"
        used.add(slug)
        user.profile_slug = slug
        user.save(update_fields=["profile_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticketmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(populate_profile_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
