# Generated by Django 6.0.1 on 2026-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticketmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
