# Generated by Django 6.0.1 on 2026-02-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_departmentinvitation'),
        ('tickets', '0015_ticketmessageattachment'),
    ]

    operations = [
    ]
