# Generated by Django 6.0.1 on 2026-02-10 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departments', to='tickets.department')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departments', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'department')},
            },
        ),
    ]
