# Generated by Django 6.0.1 on 2026-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_merge_20260210_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
