# Generated by Django 6.0.1 on 2026-02-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_department_members_ticketdepartment'),
        ('tickets', '0016_merge_20260210_1504'),
    ]

    operations = [
    ]
