# Generated by Django 6.0.1 on 2026-02-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_merge_20260220_1237'),
        ('tickets', '0017_ticketparticipant_last_read_at'),
    ]

    operations = [
    ]
