# Generated by Django 6.0.1 on 2026-02-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_user_profile_slug'),
        ('tickets', '0018_merge_20260222_1555'),
    ]

    operations = [
    ]
