# Generated by Django 6.0.1 on 2026-03-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_merge_0015_user_profile_slug_0018_merge_20260222_1555'),
        ('tickets', '0019_notification'),
    ]

    operations = [
    ]
