# Generated by Django 6.0.1 on 2026-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_merge_20260303_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketparticipant',
            name='removed_self',
            field=models.BooleanField(default=False, help_text='Whether the user removed themselves from the ticket'),
        ),
    ]
