# Generated by Django 6.0.1 on 2026-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticketparticipant_removed_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='long_message',
        ),
    ]
