# Generated by Django 5.2.7 on 2026-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_remove_notification_long_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('STAFF_REMOVED', 'Staff Removed'), ('DEPT_ASSIGNED', 'Department Assigned'), ('DEPT_REMOVED', 'Department Removed'), ('NEW_MESSAGE', 'New Message'), ('TICKET_FORWARDED', 'Ticket Forwarded')], max_length=30),
        ),
    ]
