# Generated by Django 5.2.11 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_remove_notification_long_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessageattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/'),
        ),
    ]
