# Generated by Django 6.0.1 on 2026-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('STAFF_REMOVED', 'Staff Removed'), ('DEPT_ASSIGNED', 'Department Assigned'), ('DEPT_REMOVED', 'Department Removed'), ('NEW_MESSAGE', 'New Message'), ('TICKET_FORWARDED', 'Ticket Forwarded'), ('DEPT_INVITED', 'Department Invitation Sent'), ('DEPT_MEMBER_REMOVED', 'Removed From Department'), ('DEPT_INVITE_ACCEPTED', 'Department Invite Accepted'), ('DEPT_INVITE_DECLINED', 'Department Invite Declined')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketmessageattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/'),
        ),
    ]
