# Generated by Django 6.0.1 on 2026-03-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_notification_notification_type'),
        ('tickets', '0023_alter_ticketmessageattachment_file'),
    ]

    operations = [
    ]
