# Generated by Django 6.0.1 on 2026-03-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
