# Generated by Django 6.0.1 on 2026-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_notification_notification_type_and_more'),
        ('tickets', '0024_merge_20260314_1336'),
    ]

    operations = [
    ]
