# Generated by Django 6.0.1 on 2026-03-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_merge_20260314_1336'),
        ('tickets', '0025_alter_ticketmessage_options'),
    ]

    operations = [
    ]
