# Generated by Django 6.0.1 on 2026-03-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_merge_20260315_1351'),
        ('tickets', '0026_merge_20260314_1730'),
    ]

    operations = [
    ]
