# Generated by Django 6.0.1 on 2026-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_department_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('STAFF_REMOVED', 'Staff Removed'), ('DEPT_ASSIGNED', 'Department Assigned'), ('DEPT_REMOVED', 'Department Removed'), ('NEW_MESSAGE', 'New Message'), ('TICKET_FORWARDED', 'Ticket Forwarded'), ('DEPT_INVITED', 'Department Invitation Sent'), ('DEPT_MEMBER_REMOVED', 'Removed From Department'), ('DEPT_INVITE_ACCEPTED', 'Department Invite Accepted'), ('DEPT_INVITE_DECLINED', 'Department Invite Declined'), ('TICKET_OVERDUE', 'Ticket Overdue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
